animal = "chanCHito feliz"
print(animal.upper())
print(animal.lower())
print(animal.strip().capitalize())
print(animal.title())
print(animal.strip())
print(animal.find("CH"))
print(animal.replace("CHi", "al"))
print("nCH" in animal)
print("nCH" not in animal)
